### ISSUE TITLE
Should default to current process when given no arguments

### ISSUE THREAD

**Issue by nomcopter** [airbnb/appear#3]
e.g. `appear` run without arguments should appear the pane with the current shell

**Comment by nomcopter** [comment]
Still fails on my box in 1.1.0:

```
kverdieck@kverdieck3-mbp:~/code/bedrock$ appear
/usr/local/lib/ruby/gems/2.3.0/gems/appear-1.1.0/lib/appear/command.rb:60:in `Integer': base specified for non string value (ArgumentError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/appear-1.1.0/lib/appear/command.rb:60:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/appear-1.1.0/bin/appear:11:in `<top (required)>'
        from /usr/local/bin/appear:23:in `load'
        from /usr/local/bin/appear:23:in `<main>'
```
